---

- name: test
  hosts: kube
  become: yes
  become_user: root

  tasks:
  
  - name: ip
    debug:
      msg: "{{ service_cluster_ip_range | ipaddr('next_usable') }}"
    when: inventory_hostname in groups['bastion']
    