---

- name: test
  hosts: kube
  become: yes
  become_user: root

  tasks:

  - name: Create the etcd.service file
    template:
      src: "etcd.service.j2"
      dest: "/etc/systemd/system/etcd.service"
      owner: "{{ common_owner }}"
      group: "{{ common_group }}"
      mode: 0644
    become: True
    when: inventory_hostname in groups['master']
    tags:
      - etcd