---

- name: test
  hosts: kube
  become: yes
  become_user: root

  tasks:
  
  - name: etcd vertification
    command: "ETCDCTL_API=3 {{ common_bin_directory }}/etcdctl -w table --endpoints={% for host in groups['master'] -%}{{ hostvars[host].ansible_hostname }}=https://{{ hostvars[host].ansible_eth0.ipv4.address }}:2379{%- if not loop.last %},{%- endif %}{%- endfor %} --cacert=/etc/etcd/ca.pem --cert=/etc/etcd/kubernetes.pem --key=/etc/etcd/kubernetes-key.pem endpoint status"
    become: True
    register: etcd.result
    when: inventory_hostname in groups['master']
    tags:
      - etcd

  - name: etcd etcd.result
    debug:
      msg: "{{ etcd.result }}"
    