---

- name: test
  hosts: kube
  become: yes
  become_user: root

  tasks:

  - name: Set temporary hostnames, internal and external IP address
    set_fact: 
      tempkubehosts: |
        {% for host in groups['master'] %}{{ hostvars[host].ansible_fqdn }},{{ hostvars[host].ansible_hostname }},{{ hostvars[host].ansible_eth0.ipv4.address }}{%- if not loop.last %},{%- endif %}{% endfor %}
    tags:
      - generate-ca

  - name: Replace /n in the list of hosts
    set_fact:
      kubehosts: "{{ tempkubehosts | replace('\n', '') }}"
    tags:
      - generate-ca

  - name: value
    debug:
      msg: "{{ kubehosts }}"